### PR TITLE
Fix for Chrome 66.0.3359.170

### PR DESCRIPTION
**Pull request by stefan-balke**
This fixes Chrome's new policy of only creating an `audioContext` AFTER user action.

To resolve this for `trackswitch.js`, I made `audioContext` part of the `Plugin` class.
This led to some code copy & pasting.

### CODE REVIEW

**Comment by stefan-balke** [comment]
Tested on Chrome and Safari.

**Review by faroit — COMMENTED** [review]
👍 works for me. 

Lets increase the version number to 0.1.1 for easier deployment of the fix.

**Comment by stefan-balke** [comment]
I'd like to have some tests on Windows with Firefox. @ sebastianrosenzweig can you take care of this?

**Comment by nils-werner** [comment]
The original global `audioContext` variable method was chosen because browsers don't allow more than a handful of them to be created at any given time.

What happens if you put 20 player instances on a single page, does this still work?

**Comment by stefan-balke** [comment]
I see, will try it later.

**Comment by sebastianrosenzweig** [comment]
Works on Windows with latest Chrome and Firefox.

**Comment by stefan-balke** [comment]
obsolete

**Pull request closed without merging**
