### PR TITLE
Add functionality to preselect mute and solo for audio tracks via DOM attributes

### PR DESCRIPTION
**Pull request by akustiker**
Hi there! 👋

First, I want to thank you for developing the awesome `trackswitch.js` tool. It’s been incredibly helpful for my projects!

In my specific use case, I needed the ability to preselect some audio tracks to either **mute** or **solo**, having more options to configure **mute** and **solo** settings for individual audio tracks directly from the HTML. To achieve this, I modified the following line of code: b384931fd3a741bddfecc776c29b83e7fdbf9c6b

With this update, you can now set the _initial_ **mute** and **solo** states using attributes in the `<ts-track>` DOM element, like `<ts-track title="Track" mute>` or `<ts-track title="Track" solo>`. This enhancement provides greater flexibility in managing audio tracks, particularly in applications with multiple tracks, where you want to **present a specific configuration to the listener** upfront, rather than having all tracks play simultaneously.

Here are two example use cases demonstrating how to utilize this feature:

## Example 1: Solo

Preselect **solo** for the `Drums` and `Bass` track.

```html
<div class="player">
    <p>
        An example trackswitch.js instance with preselected <b>solo</b> settings for individual tracks.
    </p>
    <img src="data/mix.png" class="seekable" data-seek-margin-left="3.5" data-seek-margin-right="4" />
    <ts-track title="Drums" data-img="data/drums.png" solo>
        <ts-source src="data/drums.mp3" type="audio/mpeg"></ts-source>
    </ts-track>
    <ts-track title="Bass" data-img="data/bass.png" solo>
        <ts-source src="data/bass.mp3" type="audio/mpeg"></ts-source>
    </ts-track>
    <ts-track title="Synth" data-img="data/synth.png">
        <ts-source src="data/synth.mp3" type="audio/mpeg"></ts-source>
    </ts-track>
    <ts-track title="Violins" data-img="data/violins.png">
        <ts-source src="data/violins.mp3" type="audio/mpeg"></ts-source>
    </ts-track>
</div>
```
Bildschirmfoto 2024-09-30 um 08 35 05

## Example 2: Mute

Preselect **mute** for the `Drums` and `Bass` track.

```html
<div class="player">
    <p>
        An example trackswitch.js instance with preselected <b>mute</b> settings for individual tracks.
    </p>
    <img src="data/mix.png" class="seekable" data-seek-margin-left="3.5" data-seek-margin-right="4" />
    <ts-track title="Drums" data-img="data/drums.png" mute>
        <ts-source src="data/drums.mp3" type="audio/mpeg"></ts-source>
    </ts-track>
    <ts-track title="Bass" data-img="data/bass.png" mute>
        <ts-source src="data/bass.mp3" type="audio/mpeg"></ts-source>
    </ts-track>
    <ts-track title="Synth" data-img="data/synth.png">
        <ts-source src="data/synth.mp3" type="audio/mpeg"></ts-source>
    </ts-track>
    <ts-track title="Violins" data-img="data/violins.png">
        <ts-source src="data/violins.mp3" type="audio/mpeg"></ts-source>
    </ts-track>
</div>
```
Bildschirmfoto 2024-09-30 um 08 34 29

---

I hope this addition proves useful to others and can be integrated into `trackswitch.js`.

Thank you for considering this contribution!

Best regards,
Peter

### CODE REVIEW

**Review by faroit — APPROVED** [review]
LGTM

**Comment by akustiker** [comment]
Hi Nils,

Yes, of course. I can add the documentation to: https://github.com/audiolabs/trackswitch.js/blob/gh-pages/configuration.md#tracks

I just have a quick question, as I’m not entirely sure how you've set up this repository: Do I need to manually update the `dist`, `js`, and `css` directories in `gh-pages` with my changes from the `main` branch (by running `grunt`), or do you have a separate deployment process for that?

I noticed there's a `.gitlab-ci.yml`, but I didn't see any GitHub Actions running. Is that correct?

Thanks!

Best,
Peter

**Comment by nils-werner** [comment]
I have no idea tbh... it's been many many years since I've touched this codebase.

**Comment by akustiker** [comment]
- I started the `master` branch inside a development Docker container `devcontainers/javascript-node:1-22-bookworm`.
- I followd the `Development` section in the `README.md` and installed `npm install -g grunt-cli`. No issues.
- `npm install` throw some errors, so I updated the `package.json`:
  + `npm install -g npm-check-updates`
  + `ncu -u`

```sh
node ➜ /workspaces/trackswitch.js $ ncu -u
Upgrading /workspaces/trackswitch.js/package.json
[====================] 18/18 100%

 font-awesome             ^4.2.0  →   ^4.7.0
 grunt                    ^1.0.1  →   ^1.6.1
 grunt-babel              ^6.0.0  →   ^8.0.0
 grunt-contrib-clean      ^1.0.0  →   ^2.0.1
 grunt-contrib-compress   ^1.4.1  →   ^2.0.0
 grunt-contrib-concat     ^1.0.1  →   ^2.1.0
 grunt-contrib-connect    ^1.0.2  →   ^5.0.0
 grunt-contrib-cssmin     ^2.0.0  →   ^5.0.0
 grunt-contrib-uglify     ^2.2.0  →   ^5.2.2
 grunt-contrib-watch      ^1.0.0  →   ^1.1.0
 grunt-exec               ^2.0.0  →   ^3.0.0
 grunt-gh-pages           ^2.0.0  →   ^4.0.0
 jquery                  >=1.9.1  →  >=3.7.1
 load-grunt-tasks         ^3.5.2  →   ^5.1.0
 node-sass                ^4.5.0  →   ^9.0.0
 time-grunt               ^1.4.0  →   ^2.0.0
 uglify-js               ^2.8.14  →  ^3.19.3

Run npm install to install new versions.
```

- `npm install`. No issues. But some warnings for deprecated packages:

```sh
node ➜ /workspaces/trackswitch.js $ npm install
npm warn deprecated osenv@0.1.5: This package is no longer supported.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated grunt-stamp@0.3.0: unmaintained
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated time-grunt@2.0.0: Deprecated because Grunt is practically unmaintained. Move on to something better. This package will continue to work with Grunt v1, but it will not receive any updates.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated node-sass@9.0.0: Node Sass is no longer supported. Please use `sass` or `sass-embedded` instead.

added 543 packages, and audited 544 packages in 1m

46 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

- `grunt dist`. This produced the `dist` directory, which I used to copy into the `gh-pages` branch.

**Note:** The files `package.json` and `package-lock.json` are not updated (yet) for this PR. But I could add them, if you like.

**Comment by akustiker** [comment]
In the `Gruntfile.js`, there is an npm task `grunt-gh-pages` that should handle copying the `dist` directory to the `gh-pages` branch. However, I don't see this task being executed anywhere (such as in a GitHub Action or similar). There's only a `.gitlab-ci.yml` file, so maybe this process used to run on the AudioLabs GitLab server? Manually copying the `dist` directory for now should be fine.

**Comment by stefan-balke** [comment]
I could offer to do a function test in a local installation so we could get this one integrate once verified.

**Comment by stefan-balke** [comment]
After going through the dependency rabbit hole I can confirm the behaviour.

One thing I noticed is that before activating the player, the mutes are not initialized.

Before:
image

After:
image


Can be left like that for now, maybe something to keep in mind. Otherwise: LGTM.

P.S.: We should follow with a PR which replaces grunt and updates the packages.

**Pull request merged**
